Add Firebase configuration check in CI workflow
Added a check for the presence of the google-services.json file in the Firebase configuration.

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -2,7 +2,7 @@ name: Flutter CI
 
 on:
   push:
-    branches: ["main"]
+    branches: [main]
 
 permissions:
   contents: write
@@ -26,6 +26,21 @@ jobs:
 
       - name: Run tests
         run: flutter test
+
+      - name: Check Firebase file
+        run: |
+          echo "Checking Firebase configuration..."
+          echo "Current directory:"
+          pwd
+          echo "Android app files:"
+          ls -la android/app
+
+          if [ -f android/app/google-services.json ]; then
+            echo "google-services.json FOUND"
+          else
+            echo "google-services.json MISSING"
+            exit 1
+          fi
 
       - name: Build APK
         run: flutter build apk --release
